/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class AddFrames extends Task {
  private transient long swigCPtr;

  protected AddFrames(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.AddFrames_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AddFrames obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_AddFrames(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AddFrames() {
    this(TasksJNI.new_AddFrames(), true);
  }

  /**
   *  Chunk to copy frames from. Default: -1
   */
  public void setChunk(int value) {
    TasksJNI.AddFrames_setChunk(swigCPtr, this, value);
  }

  /**
   *  Chunk to copy frames from. Default: -1
   */
  public int getChunk() {
    return TasksJNI.AddFrames_getChunk(swigCPtr, this);
  }

  /**
   *  Copy dense cloud. Default: true
   */
  public void setCopyDenseCloud(boolean value) {
    TasksJNI.AddFrames_setCopyDenseCloud(swigCPtr, this, value);
  }

  /**
   *  Copy dense cloud. Default: true
   */
  public boolean getCopyDenseCloud() {
    return TasksJNI.AddFrames_getCopyDenseCloud(swigCPtr, this);
  }

  /**
   *  Copy depth maps. Default: true
   */
  public void setCopyDepthMaps(boolean value) {
    TasksJNI.AddFrames_setCopyDepthMaps(swigCPtr, this, value);
  }

  /**
   *  Copy depth maps. Default: true
   */
  public boolean getCopyDepthMaps() {
    return TasksJNI.AddFrames_getCopyDepthMaps(swigCPtr, this);
  }

  /**
   *  Copy DEM. Default: true
   */
  public void setCopyElevation(boolean value) {
    TasksJNI.AddFrames_setCopyElevation(swigCPtr, this, value);
  }

  /**
   *  Copy DEM. Default: true
   */
  public boolean getCopyElevation() {
    return TasksJNI.AddFrames_getCopyElevation(swigCPtr, this);
  }

  /**
   *  Copy model. Default: true
   */
  public void setCopyModel(boolean value) {
    TasksJNI.AddFrames_setCopyModel(swigCPtr, this, value);
  }

  /**
   *  Copy model. Default: true
   */
  public boolean getCopyModel() {
    return TasksJNI.AddFrames_getCopyModel(swigCPtr, this);
  }

  /**
   *  Copy orthomosaic. Default: true
   */
  public void setCopyOrthomosaic(boolean value) {
    TasksJNI.AddFrames_setCopyOrthomosaic(swigCPtr, this, value);
  }

  /**
   *  Copy orthomosaic. Default: true
   */
  public boolean getCopyOrthomosaic() {
    return TasksJNI.AddFrames_getCopyOrthomosaic(swigCPtr, this);
  }

  /**
   *  Copy tiled model. Default: true
   */
  public void setCopyTiledModel(boolean value) {
    TasksJNI.AddFrames_setCopyTiledModel(swigCPtr, this, value);
  }

  /**
   *  Copy tiled model. Default: true
   */
  public boolean getCopyTiledModel() {
    return TasksJNI.AddFrames_getCopyTiledModel(swigCPtr, this);
  }

  /**
   *  List of frame keys to copy.
   */
  public void setFrames(int[] value) {
    TasksJNI.AddFrames_setFrames(swigCPtr, this, value);
  }

  /**
   *  List of frame keys to copy.
   */
  public int[] getFrames() { return TasksJNI.AddFrames_getFrames(swigCPtr, this); }

}
