/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class BuildUV extends Task {
  private transient long swigCPtr;

  protected BuildUV(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.BuildUV_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BuildUV obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_BuildUV(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BuildUV() {
    this(TasksJNI.new_BuildUV(), true);
  }

  /**
   *  Camera to be used for texturing in MappingCamera mode. Default: -1
   */
  public void setCamera(int value) {
    TasksJNI.BuildUV_setCamera(swigCPtr, this, value);
  }

  /**
   *  Camera to be used for texturing in MappingCamera mode. Default: -1
   */
  public int getCamera() {
    return TasksJNI.BuildUV_getCamera(swigCPtr, this);
  }

  /**
   *  Texture mapping mode. Default: MappingMode.GenericMapping
   */
  public void setMappingMode(MappingMode value) {
    TasksJNI.BuildUV_setMappingMode(swigCPtr, this, value.ordinal());
  }

  /**
   *  Texture mapping mode. Default: MappingMode.GenericMapping
   */
  public MappingMode getMappingMode() {
    return MappingMode.class.getEnumConstants()[TasksJNI.BuildUV_getMappingMode(swigCPtr, this)];
  }

  /**
   *  Number of texture pages to generate. Default: 1
   */
  public void setPageCount(int value) {
    TasksJNI.BuildUV_setPageCount(swigCPtr, this, value);
  }

  /**
   *  Number of texture pages to generate. Default: 1
   */
  public int getPageCount() {
    return TasksJNI.BuildUV_getPageCount(swigCPtr, this);
  }

  /**
   *  Expected size of texture page at texture generation step. Default: 4096
   */
  public void setTextureSize(int value) {
    TasksJNI.BuildUV_setTextureSize(swigCPtr, this, value);
  }

  /**
   *  Expected size of texture page at texture generation step. Default: 4096
   */
  public int getTextureSize() {
    return TasksJNI.BuildUV_getTextureSize(swigCPtr, this);
  }

}
