/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class CalibrateColors extends Task {
  private transient long swigCPtr;

  protected CalibrateColors(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.CalibrateColors_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CalibrateColors obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_CalibrateColors(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CalibrateColors() {
    this(TasksJNI.new_CalibrateColors(), true);
  }

  /**
   *  List of cameras to process.
   */
  public void setCameras(int[] value) {
    TasksJNI.CalibrateColors_setCameras(swigCPtr, this, value);
  }

  /**
   *  List of cameras to process.
   */
  public int[] getCameras() { return TasksJNI.CalibrateColors_getCameras(swigCPtr, this); }

  /**
   *  Source data for calibration. Default: DataSource.ModelData
   */
  public void setSourceData(DataSource value) {
    TasksJNI.CalibrateColors_setSourceData(swigCPtr, this, value.ordinal());
  }

  /**
   *  Source data for calibration. Default: DataSource.ModelData
   */
  public DataSource getSourceData() {
    return DataSource.class.getEnumConstants()[TasksJNI.CalibrateColors_getSourceData(swigCPtr, this)];
  }

  /**
   *  Calibrate white balance. Default: false
   */
  public void setWhiteBalance(boolean value) {
    TasksJNI.CalibrateColors_setWhiteBalance(swigCPtr, this, value);
  }

  /**
   *  Calibrate white balance. Default: false
   */
  public boolean getWhiteBalance() {
    return TasksJNI.CalibrateColors_getWhiteBalance(swigCPtr, this);
  }

}
