/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

/**
 * Task class containing processing parameters.
 */
public class CalibrateReflectance extends Task {
  private transient long swigCPtr;

  protected CalibrateReflectance(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.CalibrateReflectance_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CalibrateReflectance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_CalibrateReflectance(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CalibrateReflectance() {
    this(TasksJNI.new_CalibrateReflectance(), true);
  }

  /**
   *  Use calibrated reflectance panels. Default: true
   */
  public void setUseReflectancePanels(boolean value) {
    TasksJNI.CalibrateReflectance_setUseReflectancePanels(swigCPtr, this, value);
  }

  /**
   *  Use calibrated reflectance panels. Default: true
   */
  public boolean getUseReflectancePanels() {
    return TasksJNI.CalibrateReflectance_getUseReflectancePanels(swigCPtr, this);
  }

  /**
   *  Apply irradiance sensor measurements. Default: false
   */
  public void setUseSunSensor(boolean value) {
    TasksJNI.CalibrateReflectance_setUseSunSensor(swigCPtr, this, value);
  }

  /**
   *  Apply irradiance sensor measurements. Default: false
   */
  public boolean getUseSunSensor() {
    return TasksJNI.CalibrateReflectance_getUseSunSensor(swigCPtr, this);
  }

}
