/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

/**
 * Task class containing processing parameters.
 */
public class ClassifyGroundPoints extends Task {
  private transient long swigCPtr;

  protected ClassifyGroundPoints(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ClassifyGroundPoints_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClassifyGroundPoints obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ClassifyGroundPoints(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ClassifyGroundPoints() {
    this(TasksJNI.new_ClassifyGroundPoints(), true);
  }

  /**
   *  Cell size (meters). Default: 50.0
   */
  public void setCellSize(double value) {
    TasksJNI.ClassifyGroundPoints_setCellSize(swigCPtr, this, value);
  }

  /**
   *  Cell size (meters). Default: 50.0
   */
  public double getCellSize() {
    return TasksJNI.ClassifyGroundPoints_getCellSize(swigCPtr, this);
  }

  /**
   *  Maximum angle (degrees). Default: 15.0
   */
  public void setMaxAngle(double value) {
    TasksJNI.ClassifyGroundPoints_setMaxAngle(swigCPtr, this, value);
  }

  /**
   *  Maximum angle (degrees). Default: 15.0
   */
  public double getMaxAngle() {
    return TasksJNI.ClassifyGroundPoints_getMaxAngle(swigCPtr, this);
  }

  /**
   *  Maximum distance (meters). Default: 1.0
   */
  public void setMaxDistance(double value) {
    TasksJNI.ClassifyGroundPoints_setMaxDistance(swigCPtr, this, value);
  }

  /**
   *  Maximum distance (meters). Default: 1.0
   */
  public double getMaxDistance() {
    return TasksJNI.ClassifyGroundPoints_getMaxDistance(swigCPtr, this);
  }

  /**
   *  Class of points to be re-classified. Default: -1
   */
  public void setSourceClass(int value) {
    TasksJNI.ClassifyGroundPoints_setSourceClass(swigCPtr, this, value);
  }

  /**
   *  Class of points to be re-classified. Default: -1
   */
  public int getSourceClass() {
    return TasksJNI.ClassifyGroundPoints_getSourceClass(swigCPtr, this);
  }

}
