/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class CloseHoles extends Task {
  private transient long swigCPtr;

  protected CloseHoles(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.CloseHoles_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CloseHoles obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_CloseHoles(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CloseHoles() {
    this(TasksJNI.new_CloseHoles(), true);
  }

  /**
   *  Hole size threshold in percents. Default: 100
   */
  public void setLevel(int value) {
    TasksJNI.CloseHoles_setLevel(swigCPtr, this, value);
  }

  /**
   *  Hole size threshold in percents. Default: 100
   */
  public int getLevel() {
    return TasksJNI.CloseHoles_getLevel(swigCPtr, this);
  }

}
