/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

/**
 * Task class containing processing parameters.
 */
public class CompactDenseCloud extends Task {
  private transient long swigCPtr;

  protected CompactDenseCloud(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.CompactDenseCloud_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CompactDenseCloud obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_CompactDenseCloud(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CompactDenseCloud() {
    this(TasksJNI.new_CompactDenseCloud(), true);
  }

}
