/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

/**
 * Task class containing processing parameters.
 */
public class DecimateModel extends Task {
  private transient long swigCPtr;

  protected DecimateModel(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.DecimateModel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DecimateModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_DecimateModel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DecimateModel() {
    this(TasksJNI.new_DecimateModel(), true);
  }

  /**
   *  Apply to selection. Default: false
   */
  public void setApplyToSelection(boolean value) {
    TasksJNI.DecimateModel_setApplyToSelection(swigCPtr, this, value);
  }

  /**
   *  Apply to selection. Default: false
   */
  public boolean getApplyToSelection() {
    return TasksJNI.DecimateModel_getApplyToSelection(swigCPtr, this);
  }

  /**
   *  Model to process. Default: -1
   */
  public void setAsset(int value) {
    TasksJNI.DecimateModel_setAsset(swigCPtr, this, value);
  }

  /**
   *  Model to process. Default: -1
   */
  public int getAsset() {
    return TasksJNI.DecimateModel_getAsset(swigCPtr, this);
  }

  /**
   *  Target face count. Default: 200000
   */
  public void setFaceCount(int value) {
    TasksJNI.DecimateModel_setFaceCount(swigCPtr, this, value);
  }

  /**
   *  Target face count. Default: 200000
   */
  public int getFaceCount() {
    return TasksJNI.DecimateModel_getFaceCount(swigCPtr, this);
  }

}
