/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class DetectFiducials extends Task {
  private transient long swigCPtr;

  protected DetectFiducials(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.DetectFiducials_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DetectFiducials obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_DetectFiducials(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DetectFiducials() {
    this(TasksJNI.new_DetectFiducials(), true);
  }

  /**
   *  List of cameras to process.
   */
  public void setCameras(int[] value) {
    TasksJNI.DetectFiducials_setCameras(swigCPtr, this, value);
  }

  /**
   *  List of cameras to process.
   */
  public int[] getCameras() { return TasksJNI.DetectFiducials_getCameras(swigCPtr, this); }

  /**
   *  List of frames to process.
   */
  public void setFrames(int[] value) {
    TasksJNI.DetectFiducials_setFrames(swigCPtr, this, value);
  }

  /**
   *  List of frames to process.
   */
  public int[] getFrames() { return TasksJNI.DetectFiducials_getFrames(swigCPtr, this); }

  /**
   *  Generate background masks. Default: false
   */
  public void setGenerateMasks(boolean value) {
    TasksJNI.DetectFiducials_setGenerateMasks(swigCPtr, this, value);
  }

  /**
   *  Generate background masks. Default: false
   */
  public boolean getGenerateMasks() {
    return TasksJNI.DetectFiducials_getGenerateMasks(swigCPtr, this);
  }

}
