/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class DuplicateAsset extends Task {
  private transient long swigCPtr;

  protected DuplicateAsset(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.DuplicateAsset_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DuplicateAsset obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_DuplicateAsset(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DuplicateAsset() {
    this(TasksJNI.new_DuplicateAsset(), true);
  }

  /**
   *  Asset key. Default: -1
   */
  public void setAssetKey(int value) {
    TasksJNI.DuplicateAsset_setAssetKey(swigCPtr, this, value);
  }

  /**
   *  Asset key. Default: -1
   */
  public int getAssetKey() {
    return TasksJNI.DuplicateAsset_getAssetKey(swigCPtr, this);
  }

  /**
   *  Asset type. Default: DataSource.ModelData
   */
  public void setAssetType(DataSource value) {
    TasksJNI.DuplicateAsset_setAssetType(swigCPtr, this, value.ordinal());
  }

  /**
   *  Asset type. Default: DataSource.ModelData
   */
  public DataSource getAssetType() {
    return DataSource.class.getEnumConstants()[TasksJNI.DuplicateAsset_getAssetType(swigCPtr, this)];
  }

  /**
   *  Clip to boundary shapes. Default: false
   */
  public void setClipToBoundary(boolean value) {
    TasksJNI.DuplicateAsset_setClipToBoundary(swigCPtr, this, value);
  }

  /**
   *  Clip to boundary shapes. Default: false
   */
  public boolean getClipToBoundary() {
    return TasksJNI.DuplicateAsset_getClipToBoundary(swigCPtr, this);
  }

}
