/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ExportTiledModel extends Task {
  private transient long swigCPtr;

  protected ExportTiledModel(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ExportTiledModel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExportTiledModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ExportTiledModel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ExportTiledModel() {
    this(TasksJNI.new_ExportTiledModel(), true);
  }

  /**
   *  Clip tiled model to boundary shapes. Default: true
   */
  public void setClipToBoundary(boolean value) {
    TasksJNI.ExportTiledModel_setClipToBoundary(swigCPtr, this, value);
  }

  /**
   *  Clip tiled model to boundary shapes. Default: true
   */
  public boolean getClipToBoundary() {
    return TasksJNI.ExportTiledModel_getClipToBoundary(swigCPtr, this);
  }

  /**
   *  Output coordinate system.
   */
  public void setCRS(CoordinateSystem value) {
    TasksJNI.ExportTiledModel_setCRS(swigCPtr, this, CoordinateSystem.getCPtr(value), value);
  }

  /**
   *  Output coordinate system.
   */
  public CoordinateSystem getCRS() {
    return new CoordinateSystem(TasksJNI.ExportTiledModel_getCRS(swigCPtr, this), true);
  }

  /**
   *  Export format. Default: TiledModelFormat.TiledModelFormatNone
   */
  public void setFormat(TiledModelFormat value) {
    TasksJNI.ExportTiledModel_setFormat(swigCPtr, this, value.ordinal());
  }

  /**
   *  Export format. Default: TiledModelFormat.TiledModelFormatNone
   */
  public TiledModelFormat getFormat() {
    return TiledModelFormat.class.getEnumConstants()[TasksJNI.ExportTiledModel_getFormat(swigCPtr, this)];
  }

  /**
   *  Image compression parameters.
   */
  public void setImageCompression(ImageCompression value) {
    TasksJNI.ExportTiledModel_setImageCompression(swigCPtr, this, ImageCompression.getCPtr(value), value);
  }

  /**
   *  Image compression parameters.
   */
  public ImageCompression getImageCompression() {
    return new ImageCompression(TasksJNI.ExportTiledModel_getImageCompression(swigCPtr, this), true);
  }

  /**
   *  Model format for zip export. Default: ModelFormat.ModelFormatCOLLADA
   */
  public void setModelFormat(ModelFormat value) {
    TasksJNI.ExportTiledModel_setModelFormat(swigCPtr, this, value.ordinal());
  }

  /**
   *  Model format for zip export. Default: ModelFormat.ModelFormatCOLLADA
   */
  public ModelFormat getModelFormat() {
    return ModelFormat.class.getEnumConstants()[TasksJNI.ExportTiledModel_getModelFormat(swigCPtr, this)];
  }

  /**
   *  Path to output model.
   */
  public void setPath(String value) {
    TasksJNI.ExportTiledModel_setPath(swigCPtr, this, value);
  }

  /**
   *  Path to output model.
   */
  public String getPath() {
    return TasksJNI.ExportTiledModel_getPath(swigCPtr, this);
  }

  /**
   *  Raster band transformation. Default: RasterTransformType.RasterTransformNone
   */
  public void setRasterTransform(RasterTransformType value) {
    TasksJNI.ExportTiledModel_setRasterTransform(swigCPtr, this, value.ordinal());
  }

  /**
   *  Raster band transformation. Default: RasterTransformType.RasterTransformNone
   */
  public RasterTransformType getRasterTransform() {
    return RasterTransformType.class.getEnumConstants()[TasksJNI.ExportTiledModel_getRasterTransform(swigCPtr, this)];
  }

  /**
   *  Texture format. Default: ImageFormat.ImageFormatJPEG
   */
  public void setTextureFormat(ImageFormat value) {
    TasksJNI.ExportTiledModel_setTextureFormat(swigCPtr, this, value.ordinal());
  }

  /**
   *  Texture format. Default: ImageFormat.ImageFormatJPEG
   */
  public ImageFormat getTextureFormat() {
    return ImageFormat.class.getEnumConstants()[TasksJNI.ExportTiledModel_getTextureFormat(swigCPtr, this)];
  }

}
