/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ExportShapes extends Task {
  private transient long swigCPtr;

  protected ExportShapes(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ExportShapes_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExportShapes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ExportShapes(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ExportShapes() {
    this(TasksJNI.new_ExportShapes(), true);
  }

  /**
   *  Output coordinate system.
   */
  public void setCRS(CoordinateSystem value) {
    TasksJNI.ExportShapes_setCRS(swigCPtr, this, CoordinateSystem.getCPtr(value), value);
  }

  /**
   *  Output coordinate system.
   */
  public CoordinateSystem getCRS() {
    return new CoordinateSystem(TasksJNI.ExportShapes_getCRS(swigCPtr, this), true);
  }

  /**
   *  Export format. Default: ShapesFormat.ShapesFormatNone
   */
  public void setFormat(ShapesFormat value) {
    TasksJNI.ExportShapes_setFormat(swigCPtr, this, value.ordinal());
  }

  /**
   *  Export format. Default: ShapesFormat.ShapesFormatNone
   */
  public ShapesFormat getFormat() {
    return ShapesFormat.class.getEnumConstants()[TasksJNI.ExportShapes_getFormat(swigCPtr, this)];
  }

  /**
   *  A list of shape groups to export.
   */
  public void setGroups(int[] value) {
    TasksJNI.ExportShapes_setGroups(swigCPtr, this, value);
  }

  /**
   *  A list of shape groups to export.
   */
  public int[] getGroups() { return TasksJNI.ExportShapes_getGroups(swigCPtr, this); }

  /**
   *  Path to shape file.
   */
  public void setPath(String value) {
    TasksJNI.ExportShapes_setPath(swigCPtr, this, value);
  }

  /**
   *  Path to shape file.
   */
  public String getPath() {
    return TasksJNI.ExportShapes_getPath(swigCPtr, this);
  }

  /**
   *  Save polygons as polylines. Default: false
   */
  public void setPolygonsAsPolylines(boolean value) {
    TasksJNI.ExportShapes_setPolygonsAsPolylines(swigCPtr, this, value);
  }

  /**
   *  Save polygons as polylines. Default: false
   */
  public boolean getPolygonsAsPolylines() {
    return TasksJNI.ExportShapes_getPolygonsAsPolylines(swigCPtr, this);
  }

  /**
   *  Export attributes. Default: true
   */
  public void setSaveAttributes(boolean value) {
    TasksJNI.ExportShapes_setSaveAttributes(swigCPtr, this, value);
  }

  /**
   *  Export attributes. Default: true
   */
  public boolean getSaveAttributes() {
    return TasksJNI.ExportShapes_getSaveAttributes(swigCPtr, this);
  }

  /**
   *  Export labels. Default: true
   */
  public void setSaveLabels(boolean value) {
    TasksJNI.ExportShapes_setSaveLabels(swigCPtr, this, value);
  }

  /**
   *  Export labels. Default: true
   */
  public boolean getSaveLabels() {
    return TasksJNI.ExportShapes_getSaveLabels(swigCPtr, this);
  }

  /**
   *  Export points. Default: false
   */
  public void setSavePoints(boolean value) {
    TasksJNI.ExportShapes_setSavePoints(swigCPtr, this, value);
  }

  /**
   *  Export points. Default: false
   */
  public boolean getSavePoints() {
    return TasksJNI.ExportShapes_getSavePoints(swigCPtr, this);
  }

  /**
   *  Export polygons. Default: false
   */
  public void setSavePolygons(boolean value) {
    TasksJNI.ExportShapes_setSavePolygons(swigCPtr, this, value);
  }

  /**
   *  Export polygons. Default: false
   */
  public boolean getSavePolygons() {
    return TasksJNI.ExportShapes_getSavePolygons(swigCPtr, this);
  }

  /**
   *  Export polylines. Default: false
   */
  public void setSavePolylines(boolean value) {
    TasksJNI.ExportShapes_setSavePolylines(swigCPtr, this, value);
  }

  /**
   *  Export polylines. Default: false
   */
  public boolean getSavePolylines() {
    return TasksJNI.ExportShapes_getSavePolylines(swigCPtr, this);
  }

  /**
   *  Optional shift to be applied to vertex coordinates.
   */
  public void setShift(Vector3d value) {
    TasksJNI.ExportShapes_setShift(swigCPtr, this, Vector3d.getCPtr(value), value);
  }

  /**
   *  Optional shift to be applied to vertex coordinates.
   */
  public Vector3d getShift() {
    return new Vector3d(TasksJNI.ExportShapes_getShift(swigCPtr, this), true);
  }

}
