/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ExportPanorama extends Task {
  private transient long swigCPtr;

  protected ExportPanorama(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ExportPanorama_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExportPanorama obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ExportPanorama(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ExportPanorama() {
    this(TasksJNI.new_ExportPanorama(), true);
  }

  /**
   *  List of camera groups to process.
   */
  public void setCameraGroups(int[] value) {
    TasksJNI.ExportPanorama_setCameraGroups(swigCPtr, this, value);
  }

  /**
   *  List of camera groups to process.
   */
  public int[] getCameraGroups() { return TasksJNI.ExportPanorama_getCameraGroups(swigCPtr, this); }

  /**
   *  Height of output panorama. Default: 0
   */
  public void setHeight(int value) {
    TasksJNI.ExportPanorama_setHeight(swigCPtr, this, value);
  }

  /**
   *  Height of output panorama. Default: 0
   */
  public int getHeight() {
    return TasksJNI.ExportPanorama_getHeight(swigCPtr, this);
  }

  /**
   *  Image compression parameters.
   */
  public void setImageCompression(ImageCompression value) {
    TasksJNI.ExportPanorama_setImageCompression(swigCPtr, this, ImageCompression.getCPtr(value), value);
  }

  /**
   *  Image compression parameters.
   */
  public ImageCompression getImageCompression() {
    return new ImageCompression(TasksJNI.ExportPanorama_getImageCompression(swigCPtr, this), true);
  }

  /**
   *  Path to output file.
   */
  public void setPath(String value) {
    TasksJNI.ExportPanorama_setPath(swigCPtr, this, value);
  }

  /**
   *  Path to output file.
   */
  public String getPath() {
    return TasksJNI.ExportPanorama_getPath(swigCPtr, this);
  }

  /**
   *  Region to be exported.
   */
  public void setRegion(BBox2d value) {
    TasksJNI.ExportPanorama_setRegion(swigCPtr, this, BBox2d.getCPtr(value), value);
  }

  /**
   *  Region to be exported.
   */
  public BBox2d getRegion() {
    return new BBox2d(TasksJNI.ExportPanorama_getRegion(swigCPtr, this), true);
  }

  /**
   *  Panorama 3x3 orientation matrix.
   */
  public void setRotation(Matrix3x3d value) {
    TasksJNI.ExportPanorama_setRotation(swigCPtr, this, Matrix3x3d.getCPtr(value), value);
  }

  /**
   *  Panorama 3x3 orientation matrix.
   */
  public Matrix3x3d getRotation() {
    return new Matrix3x3d(TasksJNI.ExportPanorama_getRotation(swigCPtr, this), true);
  }

  /**
   *  Width of output panorama. Default: 0
   */
  public void setWidth(int value) {
    TasksJNI.ExportPanorama_setWidth(swigCPtr, this, value);
  }

  /**
   *  Width of output panorama. Default: 0
   */
  public int getWidth() {
    return TasksJNI.ExportPanorama_getWidth(swigCPtr, this);
  }

}
