/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

/**
 * Task class containing processing parameters.
 */
public class FilterDenseCloud extends Task {
  private transient long swigCPtr;

  protected FilterDenseCloud(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.FilterDenseCloud_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FilterDenseCloud obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_FilterDenseCloud(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FilterDenseCloud() {
    this(TasksJNI.new_FilterDenseCloud(), true);
  }

  /**
   *  Dense cloud key to filter. Default: -1
   */
  public void setAsset(int value) {
    TasksJNI.FilterDenseCloud_setAsset(swigCPtr, this, value);
  }

  /**
   *  Dense cloud key to filter. Default: -1
   */
  public int getAsset() {
    return TasksJNI.FilterDenseCloud_getAsset(swigCPtr, this);
  }

  /**
   *  Desired point spacing (m). Default: 0.0
   */
  public void setPointSpacing(double value) {
    TasksJNI.FilterDenseCloud_setPointSpacing(swigCPtr, this, value);
  }

  /**
   *  Desired point spacing (m). Default: 0.0
   */
  public double getPointSpacing() {
    return TasksJNI.FilterDenseCloud_getPointSpacing(swigCPtr, this);
  }

}
