/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ImportPoints extends Task {
  private transient long swigCPtr;

  protected ImportPoints(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ImportPoints_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImportPoints obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ImportPoints(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ImportPoints() {
    this(TasksJNI.new_ImportPoints(), true);
  }

  /**
   *  Calculate point normals. Default: true
   */
  public void setCalculateNormals(boolean value) {
    TasksJNI.ImportPoints_setCalculateNormals(swigCPtr, this, value);
  }

  /**
   *  Calculate point normals. Default: true
   */
  public boolean getCalculateNormals() {
    return TasksJNI.ImportPoints_getCalculateNormals(swigCPtr, this);
  }

  /**
   *  Point cloud coordinate system.
   */
  public void setCRS(CoordinateSystem value) {
    TasksJNI.ImportPoints_setCRS(swigCPtr, this, CoordinateSystem.getCPtr(value), value);
  }

  /**
   *  Point cloud coordinate system.
   */
  public CoordinateSystem getCRS() {
    return new CoordinateSystem(TasksJNI.ImportPoints_getCRS(swigCPtr, this), true);
  }

  /**
   *  Point cloud format. Default: PointsFormat.PointsFormatNone
   */
  public void setFormat(PointsFormat value) {
    TasksJNI.ImportPoints_setFormat(swigCPtr, this, value.ordinal());
  }

  /**
   *  Point cloud format. Default: PointsFormat.PointsFormatNone
   */
  public PointsFormat getFormat() {
    return PointsFormat.class.getEnumConstants()[TasksJNI.ImportPoints_getFormat(swigCPtr, this)];
  }

  /**
   *  Path to point cloud.
   */
  public void setPath(String value) {
    TasksJNI.ImportPoints_setPath(swigCPtr, this, value);
  }

  /**
   *  Path to point cloud.
   */
  public String getPath() {
    return TasksJNI.ImportPoints_getPath(swigCPtr, this);
  }

  /**
   *  Optional shift to be applied to point coordinates.
   */
  public void setShift(Vector3d value) {
    TasksJNI.ImportPoints_setShift(swigCPtr, this, Vector3d.getCPtr(value), value);
  }

  /**
   *  Optional shift to be applied to point coordinates.
   */
  public Vector3d getShift() {
    return new Vector3d(TasksJNI.ImportPoints_getShift(swigCPtr, this), true);
  }

}
