/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ImportTiledModel extends Task {
  private transient long swigCPtr;

  protected ImportTiledModel(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ImportTiledModel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImportTiledModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ImportTiledModel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ImportTiledModel() {
    this(TasksJNI.new_ImportTiledModel(), true);
  }

  /**
   *  Path to tiled model.
   */
  public void setPath(String value) {
    TasksJNI.ImportTiledModel_setPath(swigCPtr, this, value);
  }

  /**
   *  Path to tiled model.
   */
  public String getPath() {
    return TasksJNI.ImportTiledModel_getPath(swigCPtr, this);
  }

}
