/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ImportLaserScans extends Task {
  private transient long swigCPtr;

  protected ImportLaserScans(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ImportLaserScans_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImportLaserScans obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ImportLaserScans(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ImportLaserScans() {
    this(TasksJNI.new_ImportLaserScans(), true);
  }

  /**
   *  List of files to import.
   */
  public void setFilenames(String[] value) {
    TasksJNI.ImportLaserScans_setFilenames(swigCPtr, this, value);
  }

  /**
   *  List of files to import.
   */
  public String[] getFilenames() { return TasksJNI.ImportLaserScans_getFilenames(swigCPtr, this); }

  /**
   *  Point cloud format. Default: PointsFormat.PointsFormatNone
   */
  public void setFormat(PointsFormat value) {
    TasksJNI.ImportLaserScans_setFormat(swigCPtr, this, value.ordinal());
  }

  /**
   *  Point cloud format. Default: PointsFormat.PointsFormatNone
   */
  public PointsFormat getFormat() {
    return PointsFormat.class.getEnumConstants()[TasksJNI.ImportLaserScans_getFormat(swigCPtr, this)];
  }

  /**
   *  Path template to output files.
   */
  public void setImagePath(String value) {
    TasksJNI.ImportLaserScans_setImagePath(swigCPtr, this, value);
  }

  /**
   *  Path template to output files.
   */
  public String getImagePath() {
    return TasksJNI.ImportLaserScans_getImagePath(swigCPtr, this);
  }

}
