/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ImportRaster extends Task {
  private transient long swigCPtr;

  protected ImportRaster(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ImportRaster_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImportRaster obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ImportRaster(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ImportRaster() {
    this(TasksJNI.new_ImportRaster(), true);
  }

  /**
   *  Default coordinate system if not specified in GeoTIFF file.
   */
  public void setCRS(CoordinateSystem value) {
    TasksJNI.ImportRaster_setCRS(swigCPtr, this, CoordinateSystem.getCPtr(value), value);
  }

  /**
   *  Default coordinate system if not specified in GeoTIFF file.
   */
  public CoordinateSystem getCRS() {
    return new CoordinateSystem(TasksJNI.ImportRaster_getCRS(swigCPtr, this), true);
  }

  /**
   *  Path to elevation model in GeoTIFF format.
   */
  public void setPath(String value) {
    TasksJNI.ImportRaster_setPath(swigCPtr, this, value);
  }

  /**
   *  Path to elevation model in GeoTIFF format.
   */
  public String getPath() {
    return TasksJNI.ImportRaster_getPath(swigCPtr, this);
  }

  /**
   *  Type of raster layer to import. Default: DataSource.ElevationData
   */
  public void setRasterType(DataSource value) {
    TasksJNI.ImportRaster_setRasterType(swigCPtr, this, value.ordinal());
  }

  /**
   *  Type of raster layer to import. Default: DataSource.ElevationData
   */
  public DataSource getRasterType() {
    return DataSource.class.getEnumConstants()[TasksJNI.ImportRaster_getRasterType(swigCPtr, this)];
  }

}
