/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ImportMasks extends Task {
  private transient long swigCPtr;

  protected ImportMasks(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ImportMasks_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImportMasks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ImportMasks(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ImportMasks() {
    this(TasksJNI.new_ImportMasks(), true);
  }

  /**
   *  Optional list of cameras to be processed.
   */
  public void setCameras(int[] value) {
    TasksJNI.ImportMasks_setCameras(swigCPtr, this, value);
  }

  /**
   *  Optional list of cameras to be processed.
   */
  public int[] getCameras() { return TasksJNI.ImportMasks_getCameras(swigCPtr, this); }

  /**
   *  Mask operation. Default: MaskOperation.MaskOperationReplacement
   */
  public void setOperation(MaskOperation value) {
    TasksJNI.ImportMasks_setOperation(swigCPtr, this, value.ordinal());
  }

  /**
   *  Mask operation. Default: MaskOperation.MaskOperationReplacement
   */
  public MaskOperation getOperation() {
    return MaskOperation.class.getEnumConstants()[TasksJNI.ImportMasks_getOperation(swigCPtr, this)];
  }

  /**
   *  Mask file name template.
   */
  public void setPath(String value) {
    TasksJNI.ImportMasks_setPath(swigCPtr, this, value);
  }

  /**
   *  Mask file name template.
   */
  public String getPath() {
    return TasksJNI.ImportMasks_getPath(swigCPtr, this);
  }

  /**
   *  Mask source. Default: MaskSource.MaskSourceAlpha
   */
  public void setSource(MaskSource value) {
    TasksJNI.ImportMasks_setSource(swigCPtr, this, value.ordinal());
  }

  /**
   *  Mask source. Default: MaskSource.MaskSourceAlpha
   */
  public MaskSource getSource() {
    return MaskSource.class.getEnumConstants()[TasksJNI.ImportMasks_getSource(swigCPtr, this)];
  }

  /**
   *  Background masking tolerance. Default: 10
   */
  public void setTolerance(int value) {
    TasksJNI.ImportMasks_setTolerance(swigCPtr, this, value);
  }

  /**
   *  Background masking tolerance. Default: 10
   */
  public int getTolerance() {
    return TasksJNI.ImportMasks_getTolerance(swigCPtr, this);
  }

}
