/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class LoadProject extends Task {
  private transient long swigCPtr;

  protected LoadProject(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.LoadProject_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LoadProject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_LoadProject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LoadProject() {
    this(TasksJNI.new_LoadProject(), true);
  }

  /**
   *  Path to project file.
   */
  public void setPath(String value) {
    TasksJNI.LoadProject_setPath(swigCPtr, this, value);
  }

  /**
   *  Path to project file.
   */
  public String getPath() {
    return TasksJNI.LoadProject_getPath(swigCPtr, this);
  }

  /**
   *  Open project in read only mode. Default: false
   */
  public void setReadOnly(boolean value) {
    TasksJNI.LoadProject_setReadOnly(swigCPtr, this, value);
  }

  /**
   *  Open project in read only mode. Default: false
   */
  public boolean getReadOnly() {
    return TasksJNI.LoadProject_getReadOnly(swigCPtr, this);
  }

}
