/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class OptimizeCameras extends Task {
  private transient long swigCPtr;

  protected OptimizeCameras(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.OptimizeCameras_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptimizeCameras obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_OptimizeCameras(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptimizeCameras() {
    this(TasksJNI.new_OptimizeCameras(), true);
  }

  /**
   *  Enable adaptive fitting of distortion coefficients. Default: false
   */
  public void setAdaptiveFitting(boolean value) {
    TasksJNI.OptimizeCameras_setAdaptiveFitting(swigCPtr, this, value);
  }

  /**
   *  Enable adaptive fitting of distortion coefficients. Default: false
   */
  public boolean getAdaptiveFitting() {
    return TasksJNI.OptimizeCameras_getAdaptiveFitting(swigCPtr, this);
  }

  /**
   *  Enable optimization of aspect ratio. Default: false
   */
  public void setFitB1(boolean value) {
    TasksJNI.OptimizeCameras_setFitB1(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of aspect ratio. Default: false
   */
  public boolean getFitB1() {
    return TasksJNI.OptimizeCameras_getFitB1(swigCPtr, this);
  }

  /**
   *  Enable optimization of skew coefficient. Default: false
   */
  public void setFitB2(boolean value) {
    TasksJNI.OptimizeCameras_setFitB2(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of skew coefficient. Default: false
   */
  public boolean getFitB2() {
    return TasksJNI.OptimizeCameras_getFitB2(swigCPtr, this);
  }

  /**
   *  Enable optimization of additional corrections. Default: false
   */
  public void setFitCorrections(boolean value) {
    TasksJNI.OptimizeCameras_setFitCorrections(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of additional corrections. Default: false
   */
  public boolean getFitCorrections() {
    return TasksJNI.OptimizeCameras_getFitCorrections(swigCPtr, this);
  }

  /**
   *  Enable optimization of X principal point coordinates. Default: true
   */
  public void setFitCx(boolean value) {
    TasksJNI.OptimizeCameras_setFitCx(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of X principal point coordinates. Default: true
   */
  public boolean getFitCx() {
    return TasksJNI.OptimizeCameras_getFitCx(swigCPtr, this);
  }

  /**
   *  Enable optimization of Y principal point coordinates. Default: true
   */
  public void setFitCy(boolean value) {
    TasksJNI.OptimizeCameras_setFitCy(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of Y principal point coordinates. Default: true
   */
  public boolean getFitCy() {
    return TasksJNI.OptimizeCameras_getFitCy(swigCPtr, this);
  }

  /**
   *  Enable optimization of focal length coefficient. Default: true
   */
  public void setFitF(boolean value) {
    TasksJNI.OptimizeCameras_setFitF(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of focal length coefficient. Default: true
   */
  public boolean getFitF() {
    return TasksJNI.OptimizeCameras_getFitF(swigCPtr, this);
  }

  /**
   *  Enable optimization of k1 radial distortion coefficient. Default: true
   */
  public void setFitK1(boolean value) {
    TasksJNI.OptimizeCameras_setFitK1(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of k1 radial distortion coefficient. Default: true
   */
  public boolean getFitK1() {
    return TasksJNI.OptimizeCameras_getFitK1(swigCPtr, this);
  }

  /**
   *  Enable optimization of k2 radial distortion coefficient. Default: true
   */
  public void setFitK2(boolean value) {
    TasksJNI.OptimizeCameras_setFitK2(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of k2 radial distortion coefficient. Default: true
   */
  public boolean getFitK2() {
    return TasksJNI.OptimizeCameras_getFitK2(swigCPtr, this);
  }

  /**
   *  Enable optimization of k3 radial distortion coefficient. Default: true
   */
  public void setFitK3(boolean value) {
    TasksJNI.OptimizeCameras_setFitK3(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of k3 radial distortion coefficient. Default: true
   */
  public boolean getFitK3() {
    return TasksJNI.OptimizeCameras_getFitK3(swigCPtr, this);
  }

  /**
   *  Enable optimization of k3 radial distortion coefficient. Default: false
   */
  public void setFitK4(boolean value) {
    TasksJNI.OptimizeCameras_setFitK4(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of k3 radial distortion coefficient. Default: false
   */
  public boolean getFitK4() {
    return TasksJNI.OptimizeCameras_getFitK4(swigCPtr, this);
  }

  /**
   *  Enable optimization of p1 tangential distortion coefficient. Default: true
   */
  public void setFitP1(boolean value) {
    TasksJNI.OptimizeCameras_setFitP1(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of p1 tangential distortion coefficient. Default: true
   */
  public boolean getFitP1() {
    return TasksJNI.OptimizeCameras_getFitP1(swigCPtr, this);
  }

  /**
   *  Enable optimization of p2 tangential distortion coefficient. Default: true
   */
  public void setFitP2(boolean value) {
    TasksJNI.OptimizeCameras_setFitP2(swigCPtr, this, value);
  }

  /**
   *  Enable optimization of p2 tangential distortion coefficient. Default: true
   */
  public boolean getFitP2() {
    return TasksJNI.OptimizeCameras_getFitP2(swigCPtr, this);
  }

  /**
   *  Estimate tie point covariance matrices. Default: false
   */
  public void setTiepointCovariance(boolean value) {
    TasksJNI.OptimizeCameras_setTiepointCovariance(swigCPtr, this, value);
  }

  /**
   *  Estimate tie point covariance matrices. Default: false
   */
  public boolean getTiepointCovariance() {
    return TasksJNI.OptimizeCameras_getTiepointCovariance(swigCPtr, this);
  }

}
