/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class ReduceOverlap extends Task {
  private transient long swigCPtr;

  protected ReduceOverlap(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.ReduceOverlap_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReduceOverlap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_ReduceOverlap(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ReduceOverlap() {
    this(TasksJNI.new_ReduceOverlap(), true);
  }

  /**
   *  Maximum cameras to use. Default: 0
   */
  public void setMaxCameras(int value) {
    TasksJNI.ReduceOverlap_setMaxCameras(swigCPtr, this, value);
  }

  /**
   *  Maximum cameras to use. Default: 0
   */
  public int getMaxCameras() {
    return TasksJNI.ReduceOverlap_getMaxCameras(swigCPtr, this);
  }

  /**
   *  Overlap level. Default: 30
   */
  public void setOverlap(int value) {
    TasksJNI.ReduceOverlap_setOverlap(swigCPtr, this, value);
  }

  /**
   *  Overlap level. Default: 30
   */
  public int getOverlap() {
    return TasksJNI.ReduceOverlap_getOverlap(swigCPtr, this);
  }

  /**
   *  Focus on model selection. Default: false
   */
  public void setUseSelection(boolean value) {
    TasksJNI.ReduceOverlap_setUseSelection(swigCPtr, this, value);
  }

  /**
   *  Focus on model selection. Default: false
   */
  public boolean getUseSelection() {
    return TasksJNI.ReduceOverlap_getUseSelection(swigCPtr, this);
  }

}
