/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class RefineMesh extends Task {
  private transient long swigCPtr;

  protected RefineMesh(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.RefineMesh_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RefineMesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_RefineMesh(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RefineMesh() {
    this(TasksJNI.new_RefineMesh(), true);
  }

  /**
   *  List of cameras to process.
   */
  public void setCameras(int[] value) {
    TasksJNI.RefineMesh_setCameras(swigCPtr, this, value);
  }

  /**
   *  List of cameras to process.
   */
  public int[] getCameras() { return TasksJNI.RefineMesh_getCameras(swigCPtr, this); }

  /**
   *  Refinement quality. Default: 4
   */
  public void setDownscale(int value) {
    TasksJNI.RefineMesh_setDownscale(swigCPtr, this, value);
  }

  /**
   *  Refinement quality. Default: 4
   */
  public int getDownscale() {
    return TasksJNI.RefineMesh_getDownscale(swigCPtr, this);
  }

  /**
   *  Number of refinement iterations. Default: 10
   */
  public void setIterations(int value) {
    TasksJNI.RefineMesh_setIterations(swigCPtr, this, value);
  }

  /**
   *  Number of refinement iterations. Default: 10
   */
  public int getIterations() {
    return TasksJNI.RefineMesh_getIterations(swigCPtr, this);
  }

  /**
   *  Smoothing strength. Should be in range [0, 1]. Default: 0.5
   */
  public void setSmoothness(double value) {
    TasksJNI.RefineMesh_setSmoothness(swigCPtr, this, value);
  }

  /**
   *  Smoothing strength. Should be in range [0, 1]. Default: 0.5
   */
  public double getSmoothness() {
    return TasksJNI.RefineMesh_getSmoothness(swigCPtr, this);
  }

}
