/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class RunScript extends Task {
  private transient long swigCPtr;

  protected RunScript(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.RunScript_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RunScript obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_RunScript(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RunScript() {
    this(TasksJNI.new_RunScript(), true);
  }

  /**
   *  Script arguments.
   */
  public void setArgs(String value) {
    TasksJNI.RunScript_setArgs(swigCPtr, this, value);
  }

  /**
   *  Script arguments.
   */
  public String getArgs() {
    return TasksJNI.RunScript_getArgs(swigCPtr, this);
  }

  /**
   *  Script code.
   */
  public void setCode(String value) {
    TasksJNI.RunScript_setCode(swigCPtr, this, value);
  }

  /**
   *  Script code.
   */
  public String getCode() {
    return TasksJNI.RunScript_getCode(swigCPtr, this);
  }

  /**
   *  Script path.
   */
  public void setPath(String value) {
    TasksJNI.RunScript_setPath(swigCPtr, this, value);
  }

  /**
   *  Script path.
   */
  public String getPath() {
    return TasksJNI.RunScript_getPath(swigCPtr, this);
  }

}
