/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class SaveProject extends Task {
  private transient long swigCPtr;

  protected SaveProject(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.SaveProject_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SaveProject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_SaveProject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SaveProject() {
    this(TasksJNI.new_SaveProject(), true);
  }

  /**
   *  Store absolute image paths. Default: false
   */
  public void setAbsolutePaths(boolean value) {
    TasksJNI.SaveProject_setAbsolutePaths(swigCPtr, this, value);
  }

  /**
   *  Store absolute image paths. Default: false
   */
  public boolean getAbsolutePaths() {
    return TasksJNI.SaveProject_getAbsolutePaths(swigCPtr, this);
  }

  /**
   *  List of chunks to be saved.
   */
  public void setChunks(int[] value) {
    TasksJNI.SaveProject_setChunks(swigCPtr, this, value);
  }

  /**
   *  List of chunks to be saved.
   */
  public int[] getChunks() { return TasksJNI.SaveProject_getChunks(swigCPtr, this); }

  /**
   *  Project compression level. Default: 6
   */
  public void setCompression(int value) {
    TasksJNI.SaveProject_setCompression(swigCPtr, this, value);
  }

  /**
   *  Project compression level. Default: 6
   */
  public int getCompression() {
    return TasksJNI.SaveProject_getCompression(swigCPtr, this);
  }

  /**
   *  Path to project.
   */
  public void setPath(String value) {
    TasksJNI.SaveProject_setPath(swigCPtr, this, value);
  }

  /**
   *  Path to project.
   */
  public String getPath() {
    return TasksJNI.SaveProject_getPath(swigCPtr, this);
  }

  /**
   *  Project version to save.
   */
  public void setVersion(String value) {
    TasksJNI.SaveProject_setVersion(swigCPtr, this, value);
  }

  /**
   *  Project version to save.
   */
  public String getVersion() {
    return TasksJNI.SaveProject_getVersion(swigCPtr, this);
  }

}
