/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape.tasks;

import com.agisoft.metashape.*;

/**
 * Task class containing processing parameters.
 */
public class TrackMarkers extends Task {
  private transient long swigCPtr;

  protected TrackMarkers(long cPtr, boolean cMemoryOwn) {
    super(TasksJNI.TrackMarkers_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TrackMarkers obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TasksJNI.delete_TrackMarkers(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TrackMarkers() {
    this(TasksJNI.new_TrackMarkers(), true);
  }

  /**
   *  Starting frame index. Default: 0
   */
  public void setFirstFrame(int value) {
    TasksJNI.TrackMarkers_setFirstFrame(swigCPtr, this, value);
  }

  /**
   *  Starting frame index. Default: 0
   */
  public int getFirstFrame() {
    return TasksJNI.TrackMarkers_getFirstFrame(swigCPtr, this);
  }

  /**
   *  Ending frame index. Default: 0
   */
  public void setLastFrame(int value) {
    TasksJNI.TrackMarkers_setLastFrame(swigCPtr, this, value);
  }

  /**
   *  Ending frame index. Default: 0
   */
  public int getLastFrame() {
    return TasksJNI.TrackMarkers_getLastFrame(swigCPtr, this);
  }

}
