/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

import java.lang.AutoCloseable;
import java.util.Optional;
import java.util.Map;

/**
 * Attached geometry definition.
 */
public class AttachedGeometry implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AttachedGeometry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttachedGeometry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_AttachedGeometry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public AttachedGeometry() {
    this(MetashapeJNI.new_AttachedGeometry__SWIG_0(), true);
  }

  public AttachedGeometry(AttachedGeometry geometry) {
    this(MetashapeJNI.new_AttachedGeometry__SWIG_1(AttachedGeometry.getCPtr(geometry), geometry), true);
  }

  public void setType(Geometry.Type type) {
    MetashapeJNI.AttachedGeometry_setType(swigCPtr, this, type.ordinal());
  }

  public Geometry.Type getType() {
    return Geometry.Type.class.getEnumConstants()[MetashapeJNI.AttachedGeometry_getType(swigCPtr, this)];
  }

  public void setVertices(int[] vertices) {
    MetashapeJNI.AttachedGeometry_setVertices(swigCPtr, this, vertices);
  }

  public int[] getVertices() { return MetashapeJNI.AttachedGeometry_getVertices(swigCPtr, this); }

  public void setGeometries(AttachedGeometry[] geometries) {
    MetashapeJNI.AttachedGeometry_setGeometries(swigCPtr, this, SwigHelpers.cArrayUnwrap(geometries, AttachedGeometry.class));
  }

  public AttachedGeometry[] getGeometries() { return SwigHelpers.cArrayWrap(MetashapeJNI.AttachedGeometry_getGeometries(swigCPtr, this), true, AttachedGeometry.class); }

  public static AttachedGeometry makePoint(int point) {
    return new AttachedGeometry(MetashapeJNI.AttachedGeometry_makePoint(point), true);
  }

  public static AttachedGeometry makeLineString(int[] vertices) {
    return new AttachedGeometry(MetashapeJNI.AttachedGeometry_makeLineString(vertices), true);
  }

  public static AttachedGeometry makePolygon(int[] exterior_ring) {
    return new AttachedGeometry(MetashapeJNI.AttachedGeometry_makePolygon(exterior_ring), true);
  }

  public static AttachedGeometry makeMultiPoint(AttachedGeometry[] collection) {
    return new AttachedGeometry(MetashapeJNI.AttachedGeometry_makeMultiPoint(SwigHelpers.cArrayUnwrap(collection, AttachedGeometry.class)), true);
  }

  public static AttachedGeometry makeMultiLineString(AttachedGeometry[] collection) {
    return new AttachedGeometry(MetashapeJNI.AttachedGeometry_makeMultiLineString(SwigHelpers.cArrayUnwrap(collection, AttachedGeometry.class)), true);
  }

  public static AttachedGeometry makeMultiPolygon(AttachedGeometry[] collection) {
    return new AttachedGeometry(MetashapeJNI.AttachedGeometry_makeMultiPolygon(SwigHelpers.cArrayUnwrap(collection, AttachedGeometry.class)), true);
  }

  public static AttachedGeometry makeGeometryCollection(AttachedGeometry[] collection) {
    return new AttachedGeometry(MetashapeJNI.AttachedGeometry_makeGeometryCollection(SwigHelpers.cArrayUnwrap(collection, AttachedGeometry.class)), true);
  }

}
