/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

public class BBox2d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public BBox2d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BBox2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_BBox2d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BBox2d() {
    this(MetashapeJNI.new_BBox2d__SWIG_0(), true);
  }

  public BBox2d(Vector2d min, Vector2d max) {
    this(MetashapeJNI.new_BBox2d__SWIG_1(Vector2d.getCPtr(min), min, Vector2d.getCPtr(max), max), true);
  }

  /**
   *  Minimum bounding box corner.
   */
  public Vector2d getMin() {
    return new Vector2d(MetashapeJNI.BBox2d_getMin(swigCPtr, this), true);
  }

  /**
   *  Maximum bounding box corner.
   */
  public Vector2d getMax() {
    return new Vector2d(MetashapeJNI.BBox2d_getMax(swigCPtr, this), true);
  }

  /**
   *  Minimum bounding box corner.
   */
  public void setMin(Vector2d value) {
    MetashapeJNI.BBox2d_setMin(swigCPtr, this, Vector2d.getCPtr(value), value);
  }

  /**
   *  Maximum bounding box corner.
   */
  public void setMax(Vector2d value) {
    MetashapeJNI.BBox2d_setMax(swigCPtr, this, Vector2d.getCPtr(value), value);
  }

}
