/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

import java.lang.AutoCloseable;
import java.util.Optional;
import java.util.Map;

/**
 * Camera track.
 */
public class CameraTrack implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CameraTrack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CameraTrack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_CameraTrack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public CameraTrack(CameraTrack camera_track) {
    this(MetashapeJNI.new_CameraTrack(CameraTrack.getCPtr(camera_track), camera_track), true);
  }

  /**
   *  Camera track label.
   */
  public void setLabel(String label) {
    MetashapeJNI.CameraTrack_setLabel(swigCPtr, this, label);
  }

  /**
   *  Camera track label.
   */
  public String getLabel() {
    return MetashapeJNI.CameraTrack_getLabel(swigCPtr, this);
  }

  /**
   *  Current selection state.
   */
  public void setSelected(boolean state) {
    MetashapeJNI.CameraTrack_setSelected(swigCPtr, this, state);
  }

  /**
   *  Current selection state.
   */
  public boolean isSelected() {
    return MetashapeJNI.CameraTrack_isSelected(swigCPtr, this);
  }

  /**
   *  Animation duration.
   */
  public void setDuration(double duration) {
    MetashapeJNI.CameraTrack_setDuration(swigCPtr, this, duration);
  }

  /**
   *  Animation duration.
   */
  public double getDuration() {
    return MetashapeJNI.CameraTrack_getDuration(swigCPtr, this);
  }

  /**
   *  Vertical field of view in degrees.
   */
  public void setFieldOfView(double fov) {
    MetashapeJNI.CameraTrack_setFieldOfView(swigCPtr, this, fov);
  }

  /**
   *  Vertical field of view in degrees.
   */
  public double getFieldOfView() {
    return MetashapeJNI.CameraTrack_getFieldOfView(swigCPtr, this);
  }

  /**
   *  Camera track keyframes.
   */
  public void setKeyframes(int[] keys) {
    MetashapeJNI.CameraTrack_setKeyframes(swigCPtr, this, keys);
  }

  /**
   *  Camera track keyframes.
   */
  public int[] getKeyframes() { return MetashapeJNI.CameraTrack_getKeyframes(swigCPtr, this); }

  /**
   *  Camera track key.
   */
  public int getKey() {
    return MetashapeJNI.CameraTrack_getKey(swigCPtr, this);
  }

  /**
   *  Chunk container, may be null.
   */
  public Optional<Chunk> getChunk() {
    long ptr = MetashapeJNI.CameraTrack_getChunk(swigCPtr, this);
    if (ptr == 0)
        return Optional.empty();
    return Optional.of(new Chunk(ptr, true));
  }

  /**
   *  Camera track meta data.
   */
  public void setMeta(Map<String,String> meta) {
    MetashapeJNI.CameraTrack_setMeta(swigCPtr, this, meta);
  }

  /**
   *  Camera track meta data.
   */
  public Map<String,String> getMeta() { return MetashapeJNI.CameraTrack_getMeta(swigCPtr, this); }

}
