/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

public class Matrix3x3d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Matrix3x3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Matrix3x3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Matrix3x3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Matrix3x3d() {
    this(MetashapeJNI.new_Matrix3x3d__SWIG_0(), true);
  }

  public Matrix3x3d(double[][] data) {
    this(MetashapeJNI.new_Matrix3x3d__SWIG_1(data), true);
  }

  public double get(int row, int col) {
    return MetashapeJNI.Matrix3x3d_get(swigCPtr, this, row, col);
  }

  public void set(int row, int col, double value) {
    MetashapeJNI.Matrix3x3d_set(swigCPtr, this, row, col, value);
  }

  public double[][] getData() { return MetashapeJNI.Matrix3x3d_getData(swigCPtr, this); }

  public Matrix3x3d mul(Matrix3x3d other) {
    return new Matrix3x3d(MetashapeJNI.Matrix3x3d_mul__SWIG_0(swigCPtr, this, Matrix3x3d.getCPtr(other), other), true);
  }

  public Vector3d mul(Vector3d other) {
    return new Vector3d(MetashapeJNI.Matrix3x3d_mul__SWIG_1(swigCPtr, this, Vector3d.getCPtr(other), other), true);
  }

  public Matrix3x3d mul(double c) {
    return new Matrix3x3d(MetashapeJNI.Matrix3x3d_mul__SWIG_2(swigCPtr, this, c), true);
  }

  public Vector2d mulp(Vector2d other) {
    return new Vector2d(MetashapeJNI.Matrix3x3d_mulp(swigCPtr, this, Vector2d.getCPtr(other), other), true);
  }

  public Vector2d mulv(Vector2d other) {
    return new Vector2d(MetashapeJNI.Matrix3x3d_mulv(swigCPtr, this, Vector2d.getCPtr(other), other), true);
  }

  public Matrix3x3d add(Matrix3x3d other) {
    return new Matrix3x3d(MetashapeJNI.Matrix3x3d_add(swigCPtr, this, Matrix3x3d.getCPtr(other), other), true);
  }

  public Matrix3x3d sub(Matrix3x3d other) {
    return new Matrix3x3d(MetashapeJNI.Matrix3x3d_sub(swigCPtr, this, Matrix3x3d.getCPtr(other), other), true);
  }

  public Matrix3x3d inv() {
    return new Matrix3x3d(MetashapeJNI.Matrix3x3d_inv(swigCPtr, this), true);
  }

  public Matrix3x3d t() {
    return new Matrix3x3d(MetashapeJNI.Matrix3x3d_t(swigCPtr, this), true);
  }

  public double det() {
    return MetashapeJNI.Matrix3x3d_det(swigCPtr, this);
  }

  public Vector3d col(int n) {
    return new Vector3d(MetashapeJNI.Matrix3x3d_col(swigCPtr, this, n), true);
  }

  public Vector3d row(int n) {
    return new Vector3d(MetashapeJNI.Matrix3x3d_row(swigCPtr, this, n), true);
  }

}
