/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

public class Matrix4x4d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Matrix4x4d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Matrix4x4d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Matrix4x4d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Matrix4x4d() {
    this(MetashapeJNI.new_Matrix4x4d__SWIG_0(), true);
  }

  public Matrix4x4d(double[][] data) {
    this(MetashapeJNI.new_Matrix4x4d__SWIG_1(data), true);
  }

  public double get(int row, int col) {
    return MetashapeJNI.Matrix4x4d_get(swigCPtr, this, row, col);
  }

  public void set(int row, int col, double value) {
    MetashapeJNI.Matrix4x4d_set(swigCPtr, this, row, col, value);
  }

  public double[][] getData() { return MetashapeJNI.Matrix4x4d_getData(swigCPtr, this); }

  public Matrix4x4d mul(Matrix4x4d other) {
    return new Matrix4x4d(MetashapeJNI.Matrix4x4d_mul__SWIG_0(swigCPtr, this, Matrix4x4d.getCPtr(other), other), true);
  }

  public Matrix4x4d mul(double c) {
    return new Matrix4x4d(MetashapeJNI.Matrix4x4d_mul__SWIG_1(swigCPtr, this, c), true);
  }

  public Vector3d mulp(Vector3d other) {
    return new Vector3d(MetashapeJNI.Matrix4x4d_mulp(swigCPtr, this, Vector3d.getCPtr(other), other), true);
  }

  public Vector3d mulv(Vector3d other) {
    return new Vector3d(MetashapeJNI.Matrix4x4d_mulv(swigCPtr, this, Vector3d.getCPtr(other), other), true);
  }

  public Matrix4x4d inv() {
    return new Matrix4x4d(MetashapeJNI.Matrix4x4d_inv(swigCPtr, this), true);
  }

  public Matrix4x4d t() {
    return new Matrix4x4d(MetashapeJNI.Matrix4x4d_t(swigCPtr, this), true);
  }

  public double det() {
    return MetashapeJNI.Matrix4x4d_det(swigCPtr, this);
  }

  public Matrix3x3d rotation() {
    return new Matrix3x3d(MetashapeJNI.Matrix4x4d_rotation(swigCPtr, this), true);
  }

  public Vector3d translation() {
    return new Vector3d(MetashapeJNI.Matrix4x4d_translation(swigCPtr, this), true);
  }

  public double scale() {
    return MetashapeJNI.Matrix4x4d_scale(swigCPtr, this);
  }

}
