/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

/**
 * Collection of object properties.
 */
public class MetaData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public MetaData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MetaData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_MetaData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MetaData() {
    this(MetashapeJNI.new_MetaData__SWIG_0(), true);
  }

  public MetaData(MetaData meta_data) {
    this(MetashapeJNI.new_MetaData__SWIG_1(MetaData.getCPtr(meta_data), meta_data), true);
  }

  public MetaData copy() {
    return new MetaData(MetashapeJNI.MetaData_copy(swigCPtr, this), true);
  }

  public boolean contains(String key) {
    return MetashapeJNI.MetaData_contains(swigCPtr, this, key);
  }

  public String get(String key) {
    return MetashapeJNI.MetaData_get(swigCPtr, this, key);
  }

  public void set(String key, String value) {
    MetashapeJNI.MetaData_set(swigCPtr, this, key, value);
  }

  public String[] getKeys() { return MetashapeJNI.MetaData_getKeys(swigCPtr, this); }

}
