/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

public enum ModelFormat {
  ModelFormatUndefined,
  ModelFormatOBJ,
  ModelFormat3DS,
  ModelFormatVRML,
  ModelFormatPLY,
  ModelFormatCOLLADA,
  ModelFormatU3D,
  ModelFormatPDF,
  ModelFormatDXF,
  ModelFormatFBX,
  ModelFormatKMZ,
  ModelFormatCTM,
  ModelFormatSTL,
  ModelFormatDXF_3DF,
  ModelFormatTLS,
  ModelFormatABC;
}

