/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

import java.lang.AutoCloseable;
import java.util.Optional;
import java.util.Map;

/**
 * Orthomosaic.
 */
public class Orthomosaic implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Orthomosaic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Orthomosaic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Orthomosaic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public Orthomosaic(Orthomosaic orthomosaic) {
    this(MetashapeJNI.new_Orthomosaic(Orthomosaic.getCPtr(orthomosaic), orthomosaic), true);
  }

  /**
   *  Orthomosaic identifier.
   */
  public int getKey() {
    return MetashapeJNI.Orthomosaic_getKey(swigCPtr, this);
  }

  /**
   *  Chunk container, may be null.
   */
  public Optional<Chunk> getChunk() {
    long ptr = MetashapeJNI.Orthomosaic_getChunk(swigCPtr, this);
    if (ptr == 0)
        return Optional.empty();
    return Optional.of(new Chunk(ptr, true));
  }

  /**
   *  Orthomosaic label.
   */
  public void setLabel(String label) {
    MetashapeJNI.Orthomosaic_setLabel(swigCPtr, this, label);
  }

  /**
   *  Orthomosaic label.
   */
  public String getLabel() {
    return MetashapeJNI.Orthomosaic_getLabel(swigCPtr, this);
  }

  /**
   *  Path to orthomosaic data.
   */
  public String getPath() {
    return MetashapeJNI.Orthomosaic_getPath(swigCPtr, this);
  }

  /**
   *  Orthomosaic meta data.
   */
  public void setMeta(Map<String,String> meta) {
    MetashapeJNI.Orthomosaic_setMeta(swigCPtr, this, meta);
  }

  /**
   *  Orthomosaic meta data.
   */
  public Map<String,String> getMeta() { return MetashapeJNI.Orthomosaic_getMeta(swigCPtr, this); }

  /**
   *  Orthomosaic width.
   */
  public long getWidth() {
    return MetashapeJNI.Orthomosaic_getWidth(swigCPtr, this);
  }

  /**
   *  Orthomosaic height.
   */
  public long getHeight() {
    return MetashapeJNI.Orthomosaic_getHeight(swigCPtr, this);
  }

  /**
   *  Coordinates of the top left orthomosaic corner.
   */
  public Vector getTopLeft() { return MetashapeJNI.Orthomosaic_getTopLeft(swigCPtr, this); }

  /**
   *  Coordinates of the bottom right orthomosaic corner.
   */
  public Vector getBottomRight() { return MetashapeJNI.Orthomosaic_getBottomRight(swigCPtr, this); }

  /**
   *  Orthomosaic projection.
   */
  public OrthoProjection getProjection() {
    return new OrthoProjection(MetashapeJNI.Orthomosaic_getProjection(swigCPtr, this), true);
  }

  /**
   *  Orthomosaic resolution in meters.
   */
  public double getResolution() {
    return MetashapeJNI.Orthomosaic_getResolution(swigCPtr, this);
  }

  /**
   * Generate orthomosaic preview image.<br>
   * @param width Preview image width.<br>
   * @param height Preview image height.<br>
   * @return Preview image.
   */
  public Image renderPreview(long width, long height, Progress progress) {
    return new Image(MetashapeJNI.Orthomosaic_renderPreview(swigCPtr, this, width, height, progress), true);
  }

}
