/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

import java.lang.AutoCloseable;
import java.util.Optional;
import java.util.Map;

public class OrthoProjection implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OrthoProjection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OrthoProjection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_OrthoProjection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public OrthoProjection() {
    this(MetashapeJNI.new_OrthoProjection__SWIG_0(), true);
  }

  public OrthoProjection(OrthoProjection ortho_projection) {
    this(MetashapeJNI.new_OrthoProjection__SWIG_1(OrthoProjection.getCPtr(ortho_projection), ortho_projection), true);
  }

  /**
   *  Base coordinate system.
   */
  public void setCoordinateSystem(CoordinateSystem crs) {
    MetashapeJNI.OrthoProjection_setCoordinateSystem(swigCPtr, this, CoordinateSystem.getCPtr(crs), crs);
  }

  /**
   *  Base coordinate system.
   */
  public CoordinateSystem getCoordinateSystem() {
    return new CoordinateSystem(MetashapeJNI.OrthoProjection_getCoordinateSystem(swigCPtr, this), true);
  }

  /**
   *  Ortho transformation matrix.
   */
  public void setTransform(Matrix transform) {
    MetashapeJNI.OrthoProjection_setTransform(swigCPtr, this, transform);
  }

  /**
   *  Ortho transformation matrix.
   */
  public Matrix getTransform() { return MetashapeJNI.OrthoProjection_getTransform(swigCPtr, this); }

  /**
   *  Projection type.
   */
  public void setType(OrthoProjection.Type type) {
    MetashapeJNI.OrthoProjection_setType(swigCPtr, this, type.ordinal());
  }

  /**
   *  Projection type.
   */
  public OrthoProjection.Type getType() {
    return OrthoProjection.Type.class.getEnumConstants()[MetashapeJNI.OrthoProjection_getType(swigCPtr, this)];
  }

  /**
   *  Cylindrical projection radius.
   */
  public void setRadius(double radius) {
    MetashapeJNI.OrthoProjection_setRadius(swigCPtr, this, radius);
  }

  /**
   *  Cylindrical projection radius.
   */
  public double getRadius() {
    return MetashapeJNI.OrthoProjection_getRadius(swigCPtr, this);
  }

  public String getAuthority() {
    return MetashapeJNI.OrthoProjection_getAuthority(swigCPtr, this);
  }

  public String getWkt() {
    return MetashapeJNI.OrthoProjection_getWkt(swigCPtr, this);
  }

  public String getProj4() {
    return MetashapeJNI.OrthoProjection_getProj4(swigCPtr, this);
  }

  public boolean init(String wkt) {
    return MetashapeJNI.OrthoProjection_init(swigCPtr, this, wkt);
  }

  public Vector project(Vector pt) { return MetashapeJNI.OrthoProjection_project(swigCPtr, this, pt); }

  public Vector unproject(Vector pt) { return MetashapeJNI.OrthoProjection_unproject(swigCPtr, this, pt); }

  public Matrix localframe(Vector pt) { return MetashapeJNI.OrthoProjection_localframe(swigCPtr, this, pt); }

  /**
   * Transform point coordinates between coordinate systems.<br>
   * @param point Point coordinates.<br>
   * @param source Source coordinate system.<br>
   * @param target Target coordinate system.<br>
   * @return Transformed point coordinates.
   */
  public static Vector transform(Vector point, OrthoProjection source, OrthoProjection target) { return MetashapeJNI.OrthoProjection_transform(point, OrthoProjection.getCPtr(source), source, OrthoProjection.getCPtr(target), target); }

  public enum Type {
    Planar,
    Cylindrical;
  }

}
