/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

/**
 * Orthomosaic.
 */
public class Orthomosaic {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Orthomosaic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Orthomosaic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Orthomosaic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static long[] cArrayUnwrap(Orthomosaic[] arrayWrapper) {
    long[] cArray = new long[arrayWrapper.length];
    for (int i=0; i<arrayWrapper.length; i++)
      cArray[i] = Orthomosaic.getCPtr(arrayWrapper[i]);
    return cArray;
  }

  public static Orthomosaic[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    Orthomosaic[] arrayWrapper = new Orthomosaic[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new Orthomosaic(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public Orthomosaic() {
    this(MetashapeJNI.new_Orthomosaic__SWIG_0(), true);
  }

  public Orthomosaic(Orthomosaic orthomosaic) {
    this(MetashapeJNI.new_Orthomosaic__SWIG_1(Orthomosaic.getCPtr(orthomosaic), orthomosaic), true);
  }

  /**
   *  Orthomosaic identifier.
   */
  public int getKey() {
    return MetashapeJNI.Orthomosaic_getKey(swigCPtr, this);
  }

  /**
   *  Chunk container.
   */
  public Chunk getChunk() {
    long ptr = MetashapeJNI.Orthomosaic_getChunk(swigCPtr, this);
    if (ptr == 0)
        return null;
    return new Chunk(ptr, true);
  }

  /**
   *  Orthomosaic label.
   */
  public void setLabel(String label) {
    MetashapeJNI.Orthomosaic_setLabel(swigCPtr, this, label);
  }

  /**
   *  Orthomosaic label.
   */
  public String getLabel() {
    return MetashapeJNI.Orthomosaic_getLabel(swigCPtr, this);
  }

  /**
   *  Path to orthomosaic data.
   */
  public String getPath() {
    return MetashapeJNI.Orthomosaic_getPath(swigCPtr, this);
  }

  /**
   *  Orthomosaic meta data.
   */
  public void setMeta(MetaData meta) {
    MetashapeJNI.Orthomosaic_setMeta(swigCPtr, this, MetaData.getCPtr(meta), meta);
  }

  /**
   *  Orthomosaic meta data.
   */
  public MetaData getMeta() {
    return new MetaData(MetashapeJNI.Orthomosaic_getMeta(swigCPtr, this), true);
  }

  /**
   *  Orthomosaic width.
   */
  public long getWidth() {
    return MetashapeJNI.Orthomosaic_getWidth(swigCPtr, this);
  }

  /**
   *  Orthomosaic height.
   */
  public long getHeight() {
    return MetashapeJNI.Orthomosaic_getHeight(swigCPtr, this);
  }

  /**
   *  Coordinates of the top left orthomosaic corner.
   */
  public Vector2d getTopLeft() {
    return new Vector2d(MetashapeJNI.Orthomosaic_getTopLeft(swigCPtr, this), true);
  }

  /**
   *  Coordinates of the bottom right orthomosaic corner.
   */
  public Vector2d getBottomRight() {
    return new Vector2d(MetashapeJNI.Orthomosaic_getBottomRight(swigCPtr, this), true);
  }

  /**
   *  Orthomosaic projection.
   */
  public OrthoProjection getProjection() {
    return new OrthoProjection(MetashapeJNI.Orthomosaic_getProjection(swigCPtr, this), true);
  }

  /**
   *  Orthomosaic resolution in meters.
   */
  public double getResolution() {
    return MetashapeJNI.Orthomosaic_getResolution(swigCPtr, this);
  }

  /**
   * Generate orthomosaic preview image.<br>
   * @param width Preview image width.<br>
   * @param height Preview image height.<br>
   * @return Preview image.
   */
  public Image renderPreview(long width, long height, Progress progress) {
    return new Image(MetashapeJNI.Orthomosaic_renderPreview(swigCPtr, this, width, height, progress), true);
  }

}
