/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

/**
 * Photo instance.
 */
public class Photo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Photo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Photo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Photo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Photo() {
    this(MetashapeJNI.new_Photo__SWIG_0(), true);
  }

  public Photo(Photo photo) {
    this(MetashapeJNI.new_Photo__SWIG_1(Photo.getCPtr(photo), photo), true);
  }

  /**
   *  Path to the image file.
   */
  public void setPath(String path) {
    MetashapeJNI.Photo_setPath(swigCPtr, this, path);
  }

  /**
   *  Path to the image file.
   */
  public String getPath() {
    return MetashapeJNI.Photo_getPath(swigCPtr, this);
  }

  /**
   *  Layer index in the image file.
   */
  public void setLayer(long layer) {
    MetashapeJNI.Photo_setLayer(swigCPtr, this, layer);
  }

  /**
   *  Layer index in the image file.
   */
  public long getLayer() {
    return MetashapeJNI.Photo_getLayer(swigCPtr, this);
  }

  /**
   *  Photo meta data.
   */
  public void setMeta(MetaData meta) {
    MetashapeJNI.Photo_setMeta(swigCPtr, this, MetaData.getCPtr(meta), meta);
  }

  /**
   *  Photo meta data.
   */
  public MetaData getMeta() {
    return new MetaData(MetashapeJNI.Photo_getMeta(swigCPtr, this), true);
  }

  /**
   * Create new thumbnail with specified dimensions.<br>
   * @param width Thumbnail width.<br>
   * @param height Thumbnail height.
   */
  public Image createThumbnail(int width, int height) {
    long ptr = MetashapeJNI.Photo_createThumbnail(swigCPtr, this, width, height);
    if (ptr == 0)
        return null;
    return new Image(ptr, true);
  }

}
