/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

public enum PointsFormat {
  PointsFormatUndefined,
  PointsFormatOBJ,
  PointsFormatPLY,
  PointsFormatXYZ,
  PointsFormatLAS,
  PointsFormatU3D,
  PointsFormatPDF,
  PointsFormatE57,
  PointsFormatOC3,
  PointsFormatPotree,
  PointsFormatLAZ,
  PointsFormatCL3,
  PointsFormatPTS,
  PointsFormatPTX,
  PointsFormatDXF,
  PointsFormatCesium,
  PointsFormatPCD;
}

