/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

/**
 * Rational polynomial coefficients model.
 */
public class RPCModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public RPCModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RPCModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_RPCModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RPCModel() {
    this(MetashapeJNI.new_RPCModel__SWIG_0(), true);
  }

  public RPCModel(RPCModel region) {
    this(MetashapeJNI.new_RPCModel__SWIG_1(RPCModel.getCPtr(region), region), true);
  }

  public void setImageOffset(Vector2d image_offset) {
    MetashapeJNI.RPCModel_setImageOffset(swigCPtr, this, Vector2d.getCPtr(image_offset), image_offset);
  }

  public Vector2d getImageOffset() {
    return new Vector2d(MetashapeJNI.RPCModel_getImageOffset(swigCPtr, this), true);
  }

  public void setImageScale(Vector2d image_scale) {
    MetashapeJNI.RPCModel_setImageScale(swigCPtr, this, Vector2d.getCPtr(image_scale), image_scale);
  }

  public Vector2d getImageScale() {
    return new Vector2d(MetashapeJNI.RPCModel_getImageScale(swigCPtr, this), true);
  }

  public void setObjectOffset(Vector3d object_offset) {
    MetashapeJNI.RPCModel_setObjectOffset(swigCPtr, this, Vector3d.getCPtr(object_offset), object_offset);
  }

  public Vector3d getObjectOffset() {
    return new Vector3d(MetashapeJNI.RPCModel_getObjectOffset(swigCPtr, this), true);
  }

  public void setObjectScale(Vector3d object_scale) {
    MetashapeJNI.RPCModel_setObjectScale(swigCPtr, this, Vector3d.getCPtr(object_scale), object_scale);
  }

  public Vector3d getObjectScale() {
    return new Vector3d(MetashapeJNI.RPCModel_getObjectScale(swigCPtr, this), true);
  }

  public void setLineNumCoeff(double[] coeff) {
    MetashapeJNI.RPCModel_setLineNumCoeff(swigCPtr, this, coeff);
  }

  public double[] getLineNumCoeff() { return MetashapeJNI.RPCModel_getLineNumCoeff(swigCPtr, this); }

  public void setLineDenCoeff(double[] coeff) {
    MetashapeJNI.RPCModel_setLineDenCoeff(swigCPtr, this, coeff);
  }

  public double[] getLineDenCoeff() { return MetashapeJNI.RPCModel_getLineDenCoeff(swigCPtr, this); }

  public void setSampleNumCoeff(double[] coeff) {
    MetashapeJNI.RPCModel_setSampleNumCoeff(swigCPtr, this, coeff);
  }

  public double[] getSampleNumCoeff() { return MetashapeJNI.RPCModel_getSampleNumCoeff(swigCPtr, this); }

  public void setSampleDenCoeff(double[] coeff) {
    MetashapeJNI.RPCModel_setSampleDenCoeff(swigCPtr, this, coeff);
  }

  public double[] getSampleDenCoeff() { return MetashapeJNI.RPCModel_getSampleDenCoeff(swigCPtr, this); }

}
