/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

/**
 * ScalebarGroup objects define groups of multiple scale bars. The grouping is established by<br>
 * assignment of a ScalebarGroup instance to the Scalebar.group attribute of participating scale bars.
 */
public class ScalebarGroup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ScalebarGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ScalebarGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_ScalebarGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static long[] cArrayUnwrap(ScalebarGroup[] arrayWrapper) {
    long[] cArray = new long[arrayWrapper.length];
    for (int i=0; i<arrayWrapper.length; i++)
      cArray[i] = ScalebarGroup.getCPtr(arrayWrapper[i]);
    return cArray;
  }

  public static ScalebarGroup[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    ScalebarGroup[] arrayWrapper = new ScalebarGroup[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new ScalebarGroup(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public ScalebarGroup(ScalebarGroup group) {
    this(MetashapeJNI.new_ScalebarGroup(ScalebarGroup.getCPtr(group), group), true);
  }

  /**
   *  Scale bar group key.
   */
  public int getKey() {
    return MetashapeJNI.ScalebarGroup_getKey(swigCPtr, this);
  }

  /**
   *  Chunk container, may be null.
   */
  public Chunk getChunk() {
    long ptr = MetashapeJNI.ScalebarGroup_getChunk(swigCPtr, this);
    if (ptr == 0)
        return null;
    return new Chunk(ptr, true);
  }

  /**
   *  Scale bar group label.
   */
  public void setLabel(String label) {
    MetashapeJNI.ScalebarGroup_setLabel(swigCPtr, this, label);
  }

  /**
   *  Scale bar group label.
   */
  public String getLabel() {
    return MetashapeJNI.ScalebarGroup_getLabel(swigCPtr, this);
  }

  /**
   *  Current selection state.
   */
  public void setSelected(boolean state) {
    MetashapeJNI.ScalebarGroup_setSelected(swigCPtr, this, state);
  }

  /**
   *  Current selection state.
   */
  public boolean isSelected() {
    return MetashapeJNI.ScalebarGroup_isSelected(swigCPtr, this);
  }

}
