/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

/**
 * Shape group.<br>
 * <br>
 * ShapeGroup objects define groups of multiple shapes. The grouping is established by<br>
 * assignment of a ShapeGroup instance to the Shape.group attribute of participating shapes.
 */
public class ShapeGroup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ShapeGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ShapeGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_ShapeGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static long[] cArrayUnwrap(ShapeGroup[] arrayWrapper) {
    long[] cArray = new long[arrayWrapper.length];
    for (int i=0; i<arrayWrapper.length; i++)
      cArray[i] = ShapeGroup.getCPtr(arrayWrapper[i]);
    return cArray;
  }

  public static ShapeGroup[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    ShapeGroup[] arrayWrapper = new ShapeGroup[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new ShapeGroup(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public ShapeGroup(ShapeGroup group) {
    this(MetashapeJNI.new_ShapeGroup(ShapeGroup.getCPtr(group), group), true);
  }

  /**
   *  Shape group identifier.
   */
  public int getKey() {
    return MetashapeJNI.ShapeGroup_getKey(swigCPtr, this);
  }

  /**
   *  Shape group label.
   */
  public void setLabel(String label) {
    MetashapeJNI.ShapeGroup_setLabel(swigCPtr, this, label);
  }

  /**
   *  Shape group label.
   */
  public String getLabel() {
    return MetashapeJNI.ShapeGroup_getLabel(swigCPtr, this);
  }

  /**
   *  Enable flag.
   */
  public void setEnabled(boolean state) {
    MetashapeJNI.ShapeGroup_setEnabled(swigCPtr, this, state);
  }

  /**
   *  Enable flag.
   */
  public boolean isEnabled() {
    return MetashapeJNI.ShapeGroup_isEnabled(swigCPtr, this);
  }

  /**
   *  Current selection state.
   */
  public void setSelected(boolean state) {
    MetashapeJNI.ShapeGroup_setSelected(swigCPtr, this, state);
  }

  /**
   *  Current selection state.
   */
  public boolean isSelected() {
    return MetashapeJNI.ShapeGroup_isSelected(swigCPtr, this);
  }

}
