/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

public enum TargetType {
  TargetType8Bit,
  TargetType10Bit,
  TargetType12Bit,
  TargetType14Bit,
  TargetType16Bit,
  TargetType18Bit,
  TargetType20Bit,
  TargetTypeCross,
  TargetTypeCircle;
}

