/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

import java.lang.AutoCloseable;
import java.util.Optional;
import java.util.Map;

public class Task implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Task(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Task obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Task(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public Task(Task task) {
    this(MetashapeJNI.new_Task__SWIG_0(Task.getCPtr(task), task), true);
  }

  public Task(String name) {
    this(MetashapeJNI.new_Task__SWIG_1(name), true);
  }

  /**
   *  Task name.
   */
  public String getName() {
    return MetashapeJNI.Task_getName(swigCPtr, this);
  }

  /**
   *  List of configured parameter names.
   */
  public String[] getParameterNames() { return MetashapeJNI.Task_getParameterNames(swigCPtr, this); }

  /**
   * Set parameter value.
   */
  public void setParameter(String name, Object value) {
    MetashapeJNI.Task_setParameter(swigCPtr, this, name, value);
  }

  /**
   * Get parameter value.
   */
  public Object getParameter(String name) { return MetashapeJNI.Task_getParameter(swigCPtr, this, name); }

  /**
   *  Task target.
   */
  public Task.TaskTarget getTarget() {
    return Task.TaskTarget.class.getEnumConstants()[MetashapeJNI.Task_getTarget(swigCPtr, this)];
  }

  /**
   *  GPU supported flag.
   */
  public boolean isGPUSupported() {
    return MetashapeJNI.Task_isGPUSupported(swigCPtr, this);
  }

  /**
   *  Workitem count.
   */
  public int getWorkitemCount() {
    return MetashapeJNI.Task_getWorkitemCount(swigCPtr, this);
  }

  /**
   *  Workitem count.
   */
  public void setWorkitemCount(int count) {
    MetashapeJNI.Task_setWorkitemCount(swigCPtr, this, count);
  }

  /**
   * Convert task to NetworkTask.
   */
  public NetworkTask toNetworkTask() { return MetashapeJNI.Task_toNetworkTask__SWIG_0(swigCPtr, this); }

  /**
   * Convert task to NetworkTask to be applied to the chunk.
   */
  public NetworkTask toNetworkTask(Chunk chunk) { return MetashapeJNI.Task_toNetworkTask__SWIG_1(swigCPtr, this, Chunk.getCPtr(chunk), chunk); }

  /**
   * Convert task to NetworkTask to be applied to the list of chunks.
   */
  public NetworkTask toNetworkTask(Chunk[] chunks) { return MetashapeJNI.Task_toNetworkTask__SWIG_2(swigCPtr, this, SwigHelpers.cArrayUnwrap(chunks, Chunk.class)); }

  /**
   * Convert task to NetworkTask to be applied to the whole project.
   */
  public NetworkTask toNetworkTask(Document doc) { return MetashapeJNI.Task_toNetworkTask__SWIG_3(swigCPtr, this, Document.getCPtr(doc), doc); }

  /**
   * Apply task to chunk.
   */
  public void apply(Chunk chunk, Progress progress) {
    MetashapeJNI.Task_apply__SWIG_0(swigCPtr, this, Chunk.getCPtr(chunk), chunk, progress);
  }

  /**
   * Apply task to document.
   */
  public void apply(Document doc, Progress progress) {
    MetashapeJNI.Task_apply__SWIG_1(swigCPtr, this, Document.getCPtr(doc), doc, progress);
  }

  public enum TaskTarget {
    DocumentTarget,
    ChunkTarget,
    FrameTarget;
  }

}
