/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

public class Vector3uc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Vector3uc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vector3uc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Vector3uc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vector3uc() {
    this(MetashapeJNI.new_Vector3uc__SWIG_0(), true);
  }

  public Vector3uc(short x, short y, short z) {
    this(MetashapeJNI.new_Vector3uc__SWIG_1(x, y, z), true);
  }

  public Vector3uc(short[] data) {
    this(MetashapeJNI.new_Vector3uc__SWIG_2(data), true);
  }

  /**
   *  X component.
   */
  public short getX() {
    return MetashapeJNI.Vector3uc_getX(swigCPtr, this);
  }

  /**
   *  Y component.
   */
  public short getY() {
    return MetashapeJNI.Vector3uc_getY(swigCPtr, this);
  }

  /**
   *  Z component.
   */
  public short getZ() {
    return MetashapeJNI.Vector3uc_getZ(swigCPtr, this);
  }

  /**
   *  X component.
   */
  public void setX(short value) {
    MetashapeJNI.Vector3uc_setX(swigCPtr, this, value);
  }

  /**
   *  Y component.
   */
  public void setY(short value) {
    MetashapeJNI.Vector3uc_setY(swigCPtr, this, value);
  }

  /**
   *  Z component.
   */
  public void setZ(short value) {
    MetashapeJNI.Vector3uc_setZ(swigCPtr, this, value);
  }

  public short[] getData() { return MetashapeJNI.Vector3uc_getData(swigCPtr, this); }

}
