/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

public class Vector2d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Vector2d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vector2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Vector2d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static long[] cArrayUnwrap(Vector2d[] arrayWrapper) {
    long[] cArray = new long[arrayWrapper.length];
    for (int i=0; i<arrayWrapper.length; i++)
      cArray[i] = Vector2d.getCPtr(arrayWrapper[i]);
    return cArray;
  }

  public static Vector2d[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    Vector2d[] arrayWrapper = new Vector2d[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new Vector2d(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public Vector2d() {
    this(MetashapeJNI.new_Vector2d__SWIG_0(), true);
  }

  public Vector2d(double x, double y) {
    this(MetashapeJNI.new_Vector2d__SWIG_1(x, y), true);
  }

  public Vector2d(double[] data) {
    this(MetashapeJNI.new_Vector2d__SWIG_2(data), true);
  }

  public double getX() {
    return MetashapeJNI.Vector2d_getX(swigCPtr, this);
  }

  public double getY() {
    return MetashapeJNI.Vector2d_getY(swigCPtr, this);
  }

  public void setX(double value) {
    MetashapeJNI.Vector2d_setX(swigCPtr, this, value);
  }

  public void setY(double value) {
    MetashapeJNI.Vector2d_setY(swigCPtr, this, value);
  }

  public double[] getData() { return MetashapeJNI.Vector2d_getData(swigCPtr, this); }

  /**
   *  Dot product.
   */
  public double dot(Vector2d other) {
    return MetashapeJNI.Vector2d_dot(swigCPtr, this, Vector2d.getCPtr(other), other);
  }

  /**
   *  Multiplication by scalar.
   */
  public Vector2d mul(double c) {
    return new Vector2d(MetashapeJNI.Vector2d_mul(swigCPtr, this, c), true);
  }

  /**
   *  Vector sum.
   */
  public Vector2d add(Vector2d other) {
    return new Vector2d(MetashapeJNI.Vector2d_add(swigCPtr, this, Vector2d.getCPtr(other), other), true);
  }

  /**
   *  Vector difference.
   */
  public Vector2d sub(Vector2d other) {
    return new Vector2d(MetashapeJNI.Vector2d_sub(swigCPtr, this, Vector2d.getCPtr(other), other), true);
  }

  /**
   *  Vector norm.
   */
  public double norm() {
    return MetashapeJNI.Vector2d_norm(swigCPtr, this);
  }

  /**
   *  Normalized vector.
   */
  public Vector2d normalized() {
    return new Vector2d(MetashapeJNI.Vector2d_normalized(swigCPtr, this), true);
  }

}
