/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.agisoft.metashape;

/**
 * Vignetting polynomial.
 */
public class Vignetting {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Vignetting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vignetting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MetashapeJNI.delete_Vignetting(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static long[] cArrayUnwrap(Vignetting[] arrayWrapper) {
    long[] cArray = new long[arrayWrapper.length];
    for (int i=0; i<arrayWrapper.length; i++)
      cArray[i] = Vignetting.getCPtr(arrayWrapper[i]);
    return cArray;
  }

  public static Vignetting[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    Vignetting[] arrayWrapper = new Vignetting[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new Vignetting(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public Vignetting() {
    this(MetashapeJNI.new_Vignetting__SWIG_0(), true);
  }

  public Vignetting(Vignetting region) {
    this(MetashapeJNI.new_Vignetting__SWIG_1(Vignetting.getCPtr(region), region), true);
  }

  public void setCoeff(int i, int j, double value) {
    MetashapeJNI.Vignetting_setCoeff(swigCPtr, this, i, j, value);
  }

  public double getCoeff(int i, int j) {
    return MetashapeJNI.Vignetting_getCoeff(swigCPtr, this, i, j);
  }

}
